core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('sa/', include('forumsa.urls')),
    path('', include('gale.urls')),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forumsa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('posts/', views.publicacion_lista, name='publicacion_lista'),
    path('publicacion/<int:pk>/', views.publicacion_detalle, name='publicacion_detalle'),
    path('publicacion/nueva/', views.publicacion_nueva, name='publicacion_nueva'),
    path('publicacion/<int:pk>/editar/', views.publicacion_editar, name='publicacion_editar'),
    path("login/", views.login_page, name="login"),
    path("register/",  views.register_page, name="register"),
    path("logout_page/", views.logout_user, name="logout_user"),
    
]

gale/urls.py
from django.urls import path
from .views import hola, videos, home
urlpatterns = [
    path('images/', hola, name="imagenes"),
    path('videos/', videos, name="videos"),
    path('', home, name="home"),
]

forumsa/models.py
from django.db import models
from django.contrib.auth.models import User

class Publicacion(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='imagenes')
    texto = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo
    
class Comentario(models.Model):
    publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, related_name='comentarios')
    autor = models.CharField(max_length=50, blank=True, null=True)
    correo = models.EmailField()
    mensaje = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.mensaje

gale/models.py
from django.db import models

# Create your models here.

forumsa/forms.py
from .models import Publicacion
from django.contrib.auth.forms import UserCreationForm 
from .models import User
from django import forms

class PublicacionForm(forms.ModelForm):
    
    imagen = forms.ImageField(required=True)
    texto = forms.CharField(widget=forms.Textarea, required=True)

    class Meta:
        model = Publicacion
        fields = ['titulo', 'imagen', 'texto']
        labels = {
            'titulo': 'Título',
        }

class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)
            
        self.fields['email'].widget.attrs['class'] = 'w-full p-3 rounded dark:bg-gray-800'
        self.fields['username'].widget.attrs['class'] = 'w-full p-3 rounded dark:bg-gray-800'
        self.fields['password1'].widget.attrs['class'] = 'w-full p-3 rounded dark:bg-gray-800'
        self.fields['password2'].widget.attrs['class'] = 'w-full p-3 rounded dark:bg-gray-800'
            
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Repeat Password'
        

forumsa/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Publicacion, Comentario
from .forms import PublicacionForm
from django.contrib import messages 
from django.contrib.auth import authenticate, login, logout
from .models import User
from .forms import RegisterUserForm


def publicacion_lista(request):
    publicaciones = Publicacion.objects.all().order_by('-fecha_creacion')
    return render(request, 'publicacion_lista.html', {'publicaciones': publicaciones})

@login_required(login_url='login')
def publicacion_nueva(request):
    if request.method == "POST":
        form = PublicacionForm(request.POST, request.FILES)
        if form.is_valid():
            publicacion = form.save(commit=False)
            publicacion.autor = request.user
            publicacion.save()
            messages.success(request, 'Publicación publicada!')
            return redirect('publicacion_detalle', pk=publicacion.pk)
    else:
        form = PublicacionForm()
    return render(request, 'publicacion_editar.html', {'form': form})

def publicacion_detalle(request, pk):
    publicacion = get_object_or_404(Publicacion, pk=pk)
    comentarios = publicacion.comentarios.all().order_by('-fecha_creacion')
    if request.method == "POST":
        autor = request.POST.get('autor', None)
        correo = request.POST.get('correo', None)
        mensaje = request.POST.get('mensaje', None)
        Comentario.objects.create(publicacion=publicacion, autor=autor, correo=correo, mensaje=mensaje)
        return redirect('publicacion_detalle', pk=publicacion.pk)
    return render(request, 'publicacion_detalle.html', {'publicacion': publicacion, 'comentarios': comentarios})

@login_required
def publicacion_editar(request, pk):
    publicacion = get_object_or_404(Publicacion, pk=pk)
    if request.method == "POST":
        form = PublicacionForm(request.POST, request.FILES, instance=publicacion)
        if form.is_valid():
            publicacion = form.save(commit=False)
            publicacion.autor = request.user
            publicacion.save()
            return redirect('publicacion_detalle', pk=publicacion.pk)
    else:
        form = PublicacionForm(instance=publicacion)
    return render(request, 'publicacion_editar.html', {'form': form})

@login_required
def publicacion_borrar(request, pk):
    publicacion = get_object_or_404(Publicacion, pk=pk)
    publicacion.delete()
    return redirect('publicacion_lista')



def register_page(request):
    form = RegisterUserForm()
    
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        
        if form.is_valid():
            user = form.save(commit=False)
            user.email = user.email.lower()
            user.save()
            
            login(request, user)
            messages.success(request, "Account created!")
            return redirect('home')
        else:
            messages.success(request, "a error ocorred during ")
    return render(request, "register.html", {'form':form})


def logout_user(request):
    logout(request)
    messages.success(request, "NOS VEMOS DESPUES prrr")
    return redirect("login")



def login_page(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')
        
        try:
            user = User.objects.get(email=email)
        except:
            messages.success(request, "User does not exist!")
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "WELCOME BACK " + user.email)
            return redirect('home')
        else:
            messages.success(request, "USERNAME OR PASSWORD DOES NOT MATCH!")
            
    return render(request, "login.html")

gale/views.py
from django.shortcuts import render
def hola(request):
    return render(request, 'index.html')

def videos(request):
    return render(request, 'videos.html')
def home(request):
    return render(request, 'home.html')



 

templates/_base.html
<!-- templates/_base.html -->
{% load meta %}
<!DOCTYPE html>
{% load compress %}
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pser</title>
    <link rel="stylesheet" href="{% static 'estilos.css' %}">
    <link rel="stylesheet" href="{% static 'src/input.css' %}">
    <link rel="stylesheet" href="{% static 'vi.css' %}">
    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}

</head>

<body>


    <div class="bg-black">
        {% include 'layouts/navbar.html' %}
        {% if messages %}
  {% for message in messages %}
    <div id="alert-{{ forloop.counter }}" class="flex p-4 rounded-lg bg-gray-50 dark:bg-gray-800" role="alert">
      <svg aria-hidden="true" class="flex-shrink-0 w-5 h-5 text-gray-800 dark:text-gray-300" fill="currentColor"
          viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
              d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
              clip-rule="evenodd"></path>
      </svg>
      <span class="sr-only">Info</span>
      <div class="ml-3 text-sm font-medium text-gray-800 dark:text-gray-300">
          {{ message }}
      </div>
      <button type="button"
          class="close ml-auto -mx-1.5 -my-1.5 bg-gray-50 text-gray-500 rounded-lg focus:ring-2 focus:ring-gray-400 p-1.5 hover:bg-gray-200 inline-flex h-8 w-8 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-700 dark:hover:text-white"
          data-dismiss-target="#alert-{{ forloop.counter }}" aria-label="Close">
          <span class="sr-only">Dismiss</span>
          <svg aria-hidden="true" class= " close w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd"
                  d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                  clip-rule="evenodd"></path>
          </svg>
      </button>
    </div>
  {% endfor %} 
{% endif %}

    </div>

    

    





<div>   

    {% block content %}

    {% endblock content %}
    {% include 'layouts/footer.html' %}

</div>




<script>
    // Busca el botón X y agrega un listener de evento clic
    document.querySelector('.close').addEventListener('click', function() {
        // Oculta el mensaje
        document.querySelector('#myAlert').style.display = 'none';
    });
</script>



</body>

</html>

templates/layouts/footer.html
{% load static %}
<div class="border-t color-black px-4 pt-16  se mx-auto  sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8">
    <div class="  grid gap-10 row-gap-6 mb-8 sm:grid-cols-2 lg:grid-cols-4">
      <div class="sm:col-span-2">
        <a href="/" aria-label="Go home" title="Company" class="inline-flex items-center">
          <svg class="w-8 text-deep-purple-accent-400" viewBox="0 0 24 24" stroke-linejoin="round" stroke-width="2" stroke-linecap="round" stroke-miterlimit="10" stroke="currentColor" fill="none">
            <img style=" width: 70px; height: 70px;" class="jon" src="{% static 'images/pe.png' %}" alt="">
          </svg>
          <span class="ml-2 text-xl font-bold tracking-wide text-gray-800 uppercase">Forum</span>
        </a>
        <div class="mt-6 lg:max-w-sm">
          <p class="text-sm text-gray-800">
            Nuestra galería de imágenes es un paraíso para los amantes de la fotografía y la belleza.
          </p>
          <p class="mt-4 text-sm text-gray-800">
            desde animales hasta ciudades. Cada imagen cuenta una historia y está lista para ser descubierta por ti.
          </p>
        </div>
      </div>
      <div class="space-y-2 text-sm">
        <p class="text-base font-bold tracking-wide text-gray-900">Contacts</p>
        <div class="flex">
          <p class="mr-1 text-gray-800">Phone:</p>
          <a href="tel:850-123-5021" aria-label="Our phone" title="Our phone" class="transition-colors duration-300 text-deep-purple-accent-400 hover:text-deep-purple-800">por ahora no tengo :v</a>
        </div>
        <div class="flex">
          <p class="mr-1 text-gray-800">Email:</p>
          <a href="mailto:gusilengo13@gmail.com" aria-label="Our email" title="Our email" class="transition-colors duration-300 text-deep-purple-accent-400 hover:text-deep-purple-800">gusilengo13@gmail.com</a>
        </div>
        <div class="flex">
          <p class="mr-1 text-gray-800">Address:</p>
          <a href="https://www.google.com/maps" target="_blank" rel="noopener noreferrer" aria-label="Our address" title="Our address" class="transition-colors duration-300 text-deep-purple-accent-400 hover:text-deep-purple-800">
            257 Villa 31 Retiro, BA
          </a>
        </div>
      </div>
      <div>
        <span class="text-base font-bold tracking-wide text-gray-900">Social</span>
        <div class="flex items-center mt-1 space-x-3">
          <a href="https://twitter.com/PatrikPE1" target="_blanck" class="text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400">
            <svg viewBox="0 0 24 24" fill="currentColor" class="h-5">
              <path
                d="M24,4.6c-0.9,0.4-1.8,0.7-2.8,0.8c1-0.6,1.8-1.6,2.2-2.7c-1,0.6-2,1-3.1,1.2c-0.9-1-2.2-1.6-3.6-1.6 c-2.7,0-4.9,2.2-4.9,4.9c0,0.4,0,0.8,0.1,1.1C7.7,8.1,4.1,6.1,1.7,3.1C1.2,3.9,1,4.7,1,5.6c0,1.7,0.9,3.2,2.2,4.1 C2.4,9.7,1.6,9.5,1,9.1c0,0,0,0,0,0.1c0,2.4,1.7,4.4,3.9,4.8c-0.4,0.1-0.8,0.2-1.3,0.2c-0.3,0-0.6,0-0.9-0.1c0.6,2,2.4,3.4,4.6,3.4 c-1.7,1.3-3.8,2.1-6.1,2.1c-0.4,0-0.8,0-1.2-0.1c2.2,1.4,4.8,2.2,7.5,2.2c9.1,0,14-7.5,14-14c0-0.2,0-0.4,0-0.6 C22.5,6.4,23.3,5.5,24,4.6z"
              ></path>
            </svg>
          </a>
          <a href="https://www.instagram.com/davis_patrick_men/" target="_blanck" class="text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400">
            <svg viewBox="0 0 30 30" fill="currentColor" class="h-6">
              <circle cx="15" cy="15" r="4"></circle>
              <path
                d="M19.999,3h-10C6.14,3,3,6.141,3,10.001v10C3,23.86,6.141,27,10.001,27h10C23.86,27,27,23.859,27,19.999v-10   C27,6.14,23.859,3,19.999,3z M15,21c-3.309,0-6-2.691-6-6s2.691-6,6-6s6,2.691,6,6S18.309,21,15,21z M22,9c-0.552,0-1-0.448-1-1   c0-0.552,0.448-1,1-1s1,0.448,1,1C23,8.552,22.552,9,22,9z"
              ></path>
            </svg>
          </a>
          <a href="https://www.facebook.com/gringoanonim/" target="_blanck" class="text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400">
            <svg viewBox="0 0 24 24" fill="currentColor" class="h-5">
              <path
                d="M22,0H2C0.895,0,0,0.895,0,2v20c0,1.105,0.895,2,2,2h11v-9h-3v-4h3V8.413c0-3.1,1.893-4.788,4.659-4.788 c1.325,0,2.463,0.099,2.795,0.143v3.24l-1.918,0.001c-1.504,0-1.795,0.715-1.795,1.763V11h4.44l-1,4h-3.44v9H22c1.105,0,2-0.895,2-2 V2C24,0.895,23.105,0,22,0z"
              ></path>
            </svg>
          </a>
        </div>
        <p class="mt-4 text-sm text-gray-500">
          Sigueme En mis Redes Sociales si tienes alguna ayuda 
        </p>
      </div>
    </div>
    <div class="flex flex-col-reverse justify-between pt-5 pb-10 border-t lg:flex-row">
      <p class="text-sm text-gray-600">
        © Copyright 2023 PSHer reserva todos los desrechos de autor.
      </p>
      <ul class="flex flex-col mb-3 space-y-2 lg:mb-0 sm:space-y-0 sm:space-x-5 sm:flex-row">
        <li>
          <a href="https://www.instagram.com/davis_patrick_men/" class="text-sm text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">F.A.Q</a>
        </li>
        <li>
          <a href="https://admonitory-translat.000webhostapp.com/" class="text-sm text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Politica de privacidad</a>
        </li>
        <li>
          <a href="https://admonitory-translat.000webhostapp.com/" class="text-sm text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Terminos y Condiciones</a>
        </li>
      </ul>
    </div>
  </div>

templates/login.html
{% extends '_base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}




<div
	class="grid cuak max-w-screen-xl grid-cols-1 gap-8 px-8 py-16 mx-auto rounded-lg md:grid-cols-2 md:px-12 lg:px-16 xl:px-32 dark:bg-gray-800 dark:text-gray-100">
	<div class="flex flex-col justify-between">
		<div class="space-y-2">
			<h2 class="text-4xl font-bold leading-tight lg:text-5xl">Iniciar Sesión</h2>
			<div class="dark:text-gray-400"><a href="">Olvidates tu contraseña ?</a> o <a href="{% url 'register' %}">No tienes una cuenta
					?</a> </div>
		</div>
		<img src="{% static 'images/poto.png' %}" alt="" class="p-6 h-52 md:h-64">
	</div>
	<form method="POST" novalidate="" class="space-y-6 ng-untouched ng-pristine ng-valid">
		{% csrf_token %}
		<div>
			<label for="email" class="text-sm">Email</label>
			<input placeholder="Ingre su email porfavor" name="email" id="email" type="text"
				class="w-full p-3 rounded dark:bg-gray-800">
		</div>
		<div>
			<label for="password" class="">password</label>
			<input id="password" type="password" placeholder="Ingrese su contraseña porfavor" name="password"
				class="w-full p-3 rounded dark:bg-gray-800">
		</div>
		<button type="submit"
			class="w-full p-3 text-sm font-bold tracking-wide uppercase rounded dark:bg-violet-400 dark:text-gray-900">Iniciar
			sesion</button>
	</form>
</div>












{% endblock %}

templates/publicacion_detalle.html
{% extends '_base.html' %}

{% block content %}
  <div class="flex items-center justify-center p-12">
    <div class="publicacion mx-auto w-full max-w-[550px]">
      <h2 class="text-2xl font-bold mb-2">{{ publicacion.titulo }}</h2>
      <p>Publicado por {{ publicacion.autor.username }} el {{ publicacion.fecha_creacion|date:'d/m/Y H:i' }}</p>
      <img src="{{ publicacion.imagen.url }}" class="w-full my-4">
      <p class="text-lg leading-7">{{ publicacion.texto }}</p>
      <h3 class="text-xl font-semibold mt-6">Comentarios</h3>
      {% for comentario in comentarios %}
      <div class="comentario bg-gray-100 p-4 rounded-lg my-4">
        <p class="font-semibold">{{ comentario.autor }} dijo el {{ comentario.fecha_creacion|date:'d/m/Y H:i' }}</p>
        <p class="mt-2">{{ comentario.mensaje }}</p>
      </div>
      {% endfor %}
      <hr class="my-6">
      <h3 class="text-xl font-semibold mb-2">Añadir un comentario</h3>
      <form method="post">
        {% csrf_token %}
        <div class="form-group mb-4">
          <label for="id_autor" class="block mb-2 font-semibold">Nombre:</label>
          <input type="text" name="autor" id="id_autor" class="block w-full border border-gray-300 py-2 px-3 rounded-md shadow-sm" required>
        </div>
        <div class="form-group mb-4">
          <label for="id_correo" class="block mb-2 font-semibold">Correo electrónico:</label>
          <input type="email" name="correo" id="id_correo" class="block w-full border border-gray-300 py-2 px-3 rounded-md shadow-sm" required>
        </div>
        <div class="form-group mb-4">
          <label for="id_mensaje" class="block mb-2 font-semibold">Mensaje:</label>
          <textarea name="mensaje" id="id_mensaje" class="block w-full border border-gray-300 py-2 px-3 rounded-md shadow-sm" rows="3" required></textarea>
        </div>
        <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded-md">Publicar comentario</button>
      </form>
    </div>
  </div>
{% endblock %}

<div class="flex items-center justify-center p-12">
  <!-- Author: FormBold Team -->
  <!-- Learn More: https://formbold.com -->
  <div class="mx-auto w-full max-w-[550px]">
    <form action="https://formbold.com/s/FORM_ID" method="POST">
      <div class="mb-5">
        <label for="name" class="mb-3 block text-base font-medium text-[#07074D]" >
          Full Name
        </label>
        <input type="text" name="name" id="name" placeholder="Full Name" class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
        />
      </div>
      <div class="mb-5">
        <label for="email" class="mb-3 block text-base font-medium text-[#07074D]">Email Address </label>
        <input type="email" name="email" id="email" placeholder="example@domain.com" class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" />
      </div>
      <div class="mb-5">
        <label
          for="subject"
          class="mb-3 block text-base font-medium text-[#07074D]"
        >
          Subject
        </label>
        <input
          type="text"
          name="subject"
          id="subject"
          placeholder="Enter your subject"
          class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
        />
      </div>
      <div class="mb-5">
        <label for="message" class="mb-3 block text-base font-medium text-[#07074D]">Message </label> <textarea rows="4" name="message" id="message" placeholder="Type your message" class="w-full resize-none rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" > </textarea>
      </div>
      <div>
        <button
          class="hover:shadow-form rounded-md bg-[#6A64F1] py-3 px-8 text-base font-semibold text-white outline-none" > Submit </button>
      </div>
    </form>
  </div>
</div>

templates/publicacion_editar.html
{% extends '_base.html' %}

{% block content %}
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
    <h2 class="text-3xl font-bold mb-4">Editar publicación</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="flex flex-col mb-4">
        <label for="{{ form.titulo.id_for_label }}" class="font-semibold mb-2">{{ form.titulo.label }}</label>
        {{ form.titulo }}
      </div>
      <div class="flex flex-col mb-4">
        <label for="{{ form.autor.id_for_label }}" class="font-semibold mb-2">{{ form.autor.label }}</label>
        {{ form.autor }}
      </div>
      <div class="flex flex-col mb-4">
        <label for="{{ form.imagen.id_for_label }}" class="font-semibold mb-2">{{ form.imagen.label }}</label>
        {{ form.imagen }}
      </div>
      <div class="flex flex-col mb-4">
        <label for="{{ form.texto.id_for_label }}" class="font-semibold mb-2">{{ form.texto.label }}</label>
        {{ form.texto }}
      </div>
      <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mt-4">
        Guardar cambios
      </button>
    </form>
  </div>
{% endblock %}

templates/register.html
{% extends '_base.html' %}
{% load static %}
{% block title %}{% endblock  %}
{% block content %}




<div class="grid cuak max-w-screen-xl grid-cols-1 gap-8 px-8 py-16 mx-auto rounded-lg md:grid-cols-2 md:px-12 lg:px-16 xl:px-32 dark:bg-gray-800 dark:text-gray-100">
	<div class="flex flex-col justify-between">
		<div class="space-y-2">
			<h2 class="text-4xl font-bold leading-tight lg:text-5xl">Crear una cuenta</h2>
			<div class="dark:text-gray-400"><a href="">Ya tienes una cuenta?</a>, Porfavor la contraseña debe ser un poco complicada para que crees la cuenta  </div>
		</div>
		<img src="{% static 'images/poto.png' %}" alt="" class="p-6 h-52 md:h-64">
	</div>
	<form method="POST" novalidate="" class="space-y-6 ng-untouched ng-pristine ng-valid">
		{% csrf_token %}
		
		{% for field in form %}

		
		
			
		<div>
			<label for="name" class="text-sm">{{ field.label }}</label>
			{{ field }}
		</div>
		{% endfor %}
		<button type="submit" class="w-full p-3 text-sm font-bold tracking-wide uppercase rounded dark:bg-violet-400 dark:text-gray-900">Crear cuenta</button>
	</form>
</div>






<!--<input id="name" type="text" placeholder="Nombre de la cuenta" class="w-full p-3 rounded dark:bg-gray-800"> -->





{% endblock %}